apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - jafdemoaks.southeastasia.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: jafdemoaks.southeastasia.cloudapp.azure.com
    http:
      paths:
      - backend:
          serviceName: atmos-demo-node 
          servicePort: 3000
        path: /node(/|$)(.*)
      - backend:
          serviceName: test-server
          servicePort: 80
        path: /