apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.secretName }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      {{- if .Values.services }}
      {{- range $key, $val := .Values.services }}
      - backend:
          serviceName: {{ $val.name }} 
          servicePort: {{ $val.port }}
        path: {{ $val.path }}
      {{- end }}
      {{- end }}
      - backend:
          serviceName: atmos-demo-node 
          servicePort: 3000
        path: /node(/|$)(.*)