apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nginx-ingress
    meta.helm.sh/release-namespace: ingress-basic
    service.beta.kubernetes.io/azure-dns-label-name: azurejafdemo.azjafdemo.com
  creationTimestamp: null
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.40.2
    helm.sh/chart: ingress-nginx-3.7.1
  name: nginx-ingress-ingress-nginx-controller
  selfLink: /api/v1/namespaces/ingress-basic/services/nginx-ingress-ingress-nginx-controller
spec:
  externalTrafficPolicy: Cluster
  loadBalancerIP: 20.195.38.134
  ports:
  - name: http
    nodePort: 30708
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30351
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
