apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - jafdemoaks.southeastasia.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - jafdemoaks.southeastasia.cloudapp.azure.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer